version: '3.5'

services:

  code:
    image: $CLOUD_COMPUTER_IMAGE
    command: code-server --no-auth $CLOUD_COMPUTER_REPOSITORY
    restart: always
    tty: true
    labels:
      namespace: code
      tier: cloud-computer
    environment:
      COMPOSE_PROJECT_NAME: $COMPOSE_PROJECT_NAME
      DOCKER_HOST: unix:///var/run/docker.sock
      GIT_COMMITTER_EMAIL: $GIT_COMMITTER_EMAIL
      GIT_COMMITTER_NAME: $GIT_COMMITTER_NAME
      GIT_COMMITTER_EMAIL: $GIT_COMMITTER_EMAIL
      GIT_COMMITTER_NAME: $GIT_COMMITTER_NAME
      CLOUD_COMPUTER_HOST_DNS: $CLOUD_COMPUTER_HOST_DNS
      CLOUD_COMPUTER_HOST_ID: $CLOUD_COMPUTER_HOST_ID
      CLOUD_COMPUTER_TMUX: $CLOUD_COMPUTER_TMUX
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:code.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=8443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - CLOUD_COMPUTER_REPOSITORY:$CLOUD_COMPUTER_REPOSITORY
      - CLOUD_COMPUTER_TMUX:$CLOUD_COMPUTER_TMUX

volumes:
  CLOUD_COMPUTER_REPOSITORY:
  CLOUD_COMPUTER_TMUX:
