version: '3.5'

services:

  kicad:
    image: cloudnativecomputer/kicad:latest
    shm_size: 6gb
    restart: always
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:kicad.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=8080
    volumes:
      - CLOUD_COMPUTER_CLOUDSTORAGE:$CLOUD_COMPUTER_CLOUDSTORAGE
      - CLOUD_COMPUTER_HOME:$CLOUD_COMPUTER_HOME

volumes:
  CLOUD_COMPUTER_CLOUDSTORAGE:
    external: true
  CLOUD_COMPUTER_HOME:
    external: true
