version: '3.5'

services:

  terminal:
    image: $CLOUD_COMPUTER_IMAGE
    command: yarn --cwd infrastructure/tmux server
    working_dir: $CLOUD_COMPUTER_REPOSITORY
    restart: always
    shm_size: '2gb'
    tty: true
    labels:
      namespace: terminal
      tier: cloud-computer
    environment:
      COMPOSE_PROJECT_NAME: $COMPOSE_PROJECT_NAME
      DISPLAY: $CLOUD_COMPUTER_XEPHYR_DISPLAY
      DOCKER_HOST: unix:///var/run/docker.sock
      GIT_AUTHOR_EMAIL: $GIT_AUTHOR_EMAIL
      GIT_AUTHOR_NAME: $GIT_AUTHOR_NAME
      GIT_COMMITTER_EMAIL: $GIT_AUTHOR_EMAIL
      GIT_COMMITTER_NAME: $GIT_AUTHOR_NAME
      CLOUD_COMPUTER_CREDENTIALS: $CLOUD_COMPUTER_CREDENTIALS
      CLOUD_COMPUTER_HOST_DNS: $CLOUD_COMPUTER_HOST_DNS
      CLOUD_COMPUTER_HOST_ID: $CLOUD_COMPUTER_HOST_ID
      CLOUD_COMPUTER_TMUX: $CLOUD_COMPUTER_TMUX
    expose:
      - 5900
      - 8080
    labels:
      - traefik.desktop.port=5900
      - traefik.desktop.frontend.rule=Host:desktop.$CLOUD_COMPUTER_HOST_DNS
      - traefik.terminal.port=8080
      - traefik.terminal.frontend.rule=Host:terminal.$CLOUD_COMPUTER_HOST_DNS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - CLOUD_COMPUTER_CREDENTIALS:$CLOUD_COMPUTER_CREDENTIALS
      - CLOUD_COMPUTER_HOME:$CLOUD_COMPUTER_HOME
      - CLOUD_COMPUTER_NODEMON:$CLOUD_COMPUTER_NODEMON
      - CLOUD_COMPUTER_REPOSITORY:$CLOUD_COMPUTER_REPOSITORY
      - CLOUD_COMPUTER_TERRAFORM:$CLOUD_COMPUTER_TERRAFORM
      - CLOUD_COMPUTER_TMUX:$CLOUD_COMPUTER_TMUX
      - CLOUD_COMPUTER_X11:$CLOUD_COMPUTER_X11
      - CLOUD_COMPUTER_YARN:$CLOUD_COMPUTER_YARN

  container-logs:
    image: gliderlabs/logspout:latest
    restart: always
    tty: true
    labels:
      namespace: logging
      tier: cloud-computer
    environment:
      ALLOW_TTY: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  CLOUD_COMPUTER_CREDENTIALS:
  CLOUD_COMPUTER_HOME:
  CLOUD_COMPUTER_NODEMON:
  CLOUD_COMPUTER_REPOSITORY:
  CLOUD_COMPUTER_TERRAFORM:
  CLOUD_COMPUTER_TMUX:
  CLOUD_COMPUTER_X11:
  CLOUD_COMPUTER_YARN:
