version: '3.5'

services:

  terminal:
    image: $CLOUD_COMPUTER_IMAGE
    command: yarn --cwd infrastructure/tmux server
    working_dir: $CLOUD_COMPUTER_REPOSITORY
    restart: always
    shm_size: '2gb'
    tty: true
    labels:
      namespace: terminal
      tier: cloud-computer
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      GIT_COMMITTER_EMAIL: $GIT_COMMITTER_EMAIL
      GIT_COMMITTER_NAME: $GIT_COMMITTER_NAME
      GIT_COMMITTER_EMAIL: $GIT_COMMITTER_EMAIL
      GIT_COMMITTER_NAME: $GIT_COMMITTER_NAME
      CLOUD_COMPUTER_CREDENTIALS: $CLOUD_COMPUTER_CREDENTIALS
      CLOUD_COMPUTER_DNS_EMAIL: $CLOUD_COMPUTER_DNS_EMAIL
      CLOUD_COMPUTER_DNS_TOKEN: $CLOUD_COMPUTER_DNS_TOKEN
      CLOUD_COMPUTER_DNS_ZONE: $CLOUD_COMPUTER_DNS_ZONE
      CLOUD_COMPUTER_HOST_DNS: $CLOUD_COMPUTER_HOST_DNS
      CLOUD_COMPUTER_HOST_ID: $CLOUD_COMPUTER_HOST_ID
      CLOUD_COMPUTER_TMUX: $CLOUD_COMPUTER_TMUX
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:terminal.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - CLOUD_COMPUTER_CACHE_YARN:$CLOUD_COMPUTER_CACHE_YARN
      - CLOUD_COMPUTER_CACHE_ZSH:$CLOUD_COMPUTER_CACHE_ZSH
      - CLOUD_COMPUTER_CREDENTIALS:$CLOUD_COMPUTER_CREDENTIALS
      - CLOUD_COMPUTER_CLOUDSTORAGE:$CLOUD_COMPUTER_CLOUDSTORAGE
      - CLOUD_COMPUTER_HOME:$CLOUD_COMPUTER_HOME
      - CLOUD_COMPUTER_NODEMON:$CLOUD_COMPUTER_NODEMON
      - CLOUD_COMPUTER_REPOSITORY:$CLOUD_COMPUTER_REPOSITORY
      - CLOUD_COMPUTER_STATE_JUMP:$CLOUD_COMPUTER_STATE_JUMP
      - CLOUD_COMPUTER_TERRAFORM:$CLOUD_COMPUTER_TERRAFORM
      - CLOUD_COMPUTER_TMUX:$CLOUD_COMPUTER_TMUX
      - CLOUD_COMPUTER_X11:$CLOUD_COMPUTER_X11
      - CLOUD_COMPUTER_YARN:$CLOUD_COMPUTER_YARN

  container-logs:
    image: gliderlabs/logspout:latest
    restart: always
    tty: true
    labels:
      namespace: logging
      tier: cloud-computer
    environment:
      ALLOW_TTY: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  CLOUD_COMPUTER_CACHE_YARN:
    external: true
  CLOUD_COMPUTER_CACHE_ZSH:
    external: true
  CLOUD_COMPUTER_CREDENTIALS:
    external: true
  CLOUD_COMPUTER_HOME:
    external: true
  CLOUD_COMPUTER_NODEMON:
    external: true
  CLOUD_COMPUTER_REPOSITORY:
    external: true
  CLOUD_COMPUTER_CLOUDSTORAGE:
    external: true
  CLOUD_COMPUTER_STATE_JUMP:
    external: true
  CLOUD_COMPUTER_TERRAFORM:
    external: true
  CLOUD_COMPUTER_TMUX:
    external: true
  CLOUD_COMPUTER_X11:
    external: true
  CLOUD_COMPUTER_YARN:
    external: true
